### PR TITLE
Implement anchor routing for categories

### PR DESCRIPTION
**Pull request by ikonst**
Routes to categories from the location hash, so that you could send a link to a category.

### CODE REVIEW

**Comment by ikonst** [comment]
cc @mohsen1 this is react and I have no idea what I'm doing

**Comment by mohsen1** [comment]
Does this work when you refresh the page?

**Comment by ikonst** [comment]
Yep, why wouldn't it?

**Comment by mohsen1** [comment]
I mean when you go to `#ios` and only see iOS  project, will refreshing still show iOS projects only?

**Comment by ikonst** [comment]
Yep, it does. (That's exactly what I was implementing.)

**Pull request merged**
